server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/pjtback?serverTimezone=UTC
    password: root
    username: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


  flyway:
    enabled: true

application:
  base-url: http://locahost:4200
